[".local/share/ls_colors/"]
type = "git-repo"
url = "https://github.com/trapd00r/LS_COLORS.git"
refreshPeriod = "168h"

[".config/bat/themes/Tokyo-Night.tmTheme"]
type = "file"
url = "https://raw.githubusercontent.com/enkia/enki-theme/master/scheme/Enki-Tokyo-Night.tmTheme"
refreshPeriod = "168h"

[".config/kitty/kitty_tokyonight_day.conf"]
type = "file"
url = "https://raw.githubusercontent.com/folke/tokyonight.nvim/main/extras/kitty_tokyonight_day.conf"
refreshPeriod = "168h"

[".config/kitty/kitty_tokyonight_night.conf"]
type = "file"
url = "https://raw.githubusercontent.com/folke/tokyonight.nvim/main/extras/kitty_tokyonight_night.conf"
refreshPeriod = "168h"

[".config/kitty/kitty_tokyonight_storm.conf"]
type = "file"
url = "https://raw.githubusercontent.com/folke/tokyonight.nvim/main/extras/kitty_tokyonight_storm.conf"
refreshPeriod = "168h"

[".local/bin/nofetch"]
type = "file"
url = "https://raw.githubusercontent.com/jnats/nofetch/main/nofetch"
executable = true
refreshPeriod = "168h"

[".local/bin/unimatrix"]
type = "file"
url = "https://github.com/will8211/unimatrix/raw/master/unimatrix.py"
executable = true
refreshPeriod = "168h"

[".config/zsh/zplug/"]
type = "git-repo"
url = "https://github.com/zplug/zplug.git"
refreshPeriod = "168h"

[".config/zsh/plugins/romkatv/powerlevel10k/"]
type = "git-repo"
url = "https://github.com/romkatv/powerlevel10k.git"
refreshPeriod = "168h"
[".config/zsh/plugins/romkatv/powerlevel10k/".clone]
args = ["--depth=1"]
[".config/zsh/plugins/romkatv/powerlevel10k/".pull]
args = ["--depth=1"]

[".config/zsh/plugins/zsh-users/zsh-syntax-highlighting"]
type = "git-repo"
url = "https://github.com/zsh-users/zsh-syntax-highlighting.git"
refreshPeriod = "168h"
[".config/zsh/plugins/zsh-users/zsh-autosuggestions"]
type = "git-repo"
url = "https://github.com/zsh-users/zsh-autosuggestions.git"
refreshPeriod = "168h"
[".config/zsh/plugins/zsh-users/zsh-completions"]
type = "git-repo"
url = "https://github.com/zsh-users/zsh-completions.git"
refreshPeriod = "168h"


[".config/boxes/boxes-config_copy"]
type = "file"
url = "https://raw.githubusercontent.com/ascii-boxes/boxes/master/boxes-config"
refreshPeriod = "168h"

[".config/boxes/boxes-config"]
type = "file"
url = "https://raw.githubusercontent.com/ascii-boxes/boxes/master/boxes-config"
refreshPeriod = "168h"
