[".local/share/ls_colors/"]
type = "git-repo"
url = "https://github.com/trapd00r/LS_COLORS.git"
refreshPeriod = "168h"

[".config/boxes/boxes-config"]
type = "file"
url = "https://raw.githubusercontent.com/ascii-boxes/boxes/master/boxes-config"
refreshPeriod = "168h"

[".config/kitty/kitty_tokyonight_day.conf"]
type = "file"
url = "https://raw.githubusercontent.com/folke/tokyonight.nvim/main/extras/kitty_tokyonight_day.conf"

[".config/kitty/kitty_tokyonight_night.conf"]
type = "file"
url = "https://raw.githubusercontent.com/folke/tokyonight.nvim/main/extras/kitty_tokyonight_night.conf"

[".config/kitty/kitty_tokyonight_storm.conf"]
type = "file"
url = "https://raw.githubusercontent.com/folke/tokyonight.nvim/main/extras/kitty_tokyonight_storm.conf"

[".local/bin/nofetch"]
type = "file"
url = "https://raw.githubusercontent.com/jnats/nofetch/main/nofetch"
executable = true

[".local/bin/unimatrix"]
type = "file"
url = "https://github.com/will8211/unimatrix/raw/master/unimatrix.py"
executable = true
