[".local/share/ls_colors/"]
type = "git-repo"
url = "https://github.com/trapd00r/LS_COLORS.git"
refreshPeriod = "168h"

[".config/boxes/boxes-config"]
type = "file"
url = "https://raw.githubusercontent.com/ascii-boxes/boxes/master/boxes-config"
refreshPeriod = "168h"

[".config/kitty/kitty_tokyonight_night.conf"]
type = "file"
url = "https://raw.githubusercontent.om/folke/tokyonight.nvim/main/extras/kitty_tokyonight_night.conf"

[".config/kitty/kitty_tokyonight_storm.conf"]
type = "file"
url = "https://raw.githubusercontent.com/folke/tokyonight.nvim/main/extras/kitty_tokyonight_storm.conf"
