#!/usr/bin/env zsh
set -eu

XDG_CONFIG_HOME=$HOME/.config
NPM_CONFIG_USERCONFIG=$XDG_CONFIG_HOME/npm/config

XDG_CACHE_HOME=$HOME/.cache
NPM_CONFIG_CACHE=$XDG_CACHE_HOME/npm

XDG_DATA_HOME=$HOME/.local/share
CARGO_HOME=$XDG_DATA_HOME/cargo
RUSTUP_HOME=$XDG_DATA_HOME/rustup

XDG_RUNTIME_DIR=/run/user/$UID
NPM_CONFIG_TMP=$XDG_RUNTIME_DIR/npm

curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
source $XDG_DATA_HOME/cargo/env
rm -f $HOME/.profile

cargo install --locked code-minimap bat

bash <(curl -s https://raw.githubusercontent.com/lunarvim/lunarvim/master/utils/installer/install.sh) -y
rm -rf $XDG_CONFIG_HOME/lvim/*

if [[ -x $(command -v chezmoi) ]]; then >&2
    chezmoi init --apply git@github.com:jdsurrett/dotfiles.git
fi

if ! [[ -x $(command -v chezmoi) ]]; then >&2
    sh -c "$(curl -fsLS chezmoi.io/get)" -- init --apply git@github.com:jdsurrett/dotfiles.git
fi
