#!/usr/bin/env zsh
set -eu

if ! [[ -n "$@" ]]; then >&2 echo "Please set chezmoi github username" && return; fi

if ! [[ -x $(command -v chezmoi) ]]; then >&2
    sh -c "$(curl -fsLS chezmoi.io/get)" -- $@
    return
else
    chezmoi $@
    return
fi
