#!/usr/bin/env zsh
set -eu

XDG_CONFIG_HOME=$HOME/.config
XDG_CACHE_HOME=$HOME/.cache
XDG_DATA_HOME=$HOME/.local/share
XDG_STATE_HOME=$HOME/.local/state
CARGO_HOME=$XDG_DATA_HOME/cargo
RUSTUP_HOME=$XDG_DATA_HOME/rustup
NPM_CONFIG_USERCONFIG=$XDG_CONFIG_HOME/npm/config
NPM_CONFIG_CACHE=$XDG_CACHE_HOME/npm

# I dont think I need this but, I'm going to keep it for now 
XDG_RUNTIME_DIR=/run/user/$UID
NPM_CONFIG_TMP=$XDG_RUNTIME_DIR/npm

curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
source $XDG_DATA_HOME/cargo/env
rm -f $HOME/.profile

bash <(curl -s https://raw.githubusercontent.com/lunarvim/lunarvim/master/utils/installer/install.sh) -y
rm -rf $XDG_CONFIG_HOME/lvim/*
chezmoi apply --verbose --force
