#!/bin/sh

# Values

set_colors() {
    c1="$(color "$1")${ascii_bold}"
    c2="$(color "$2")${ascii_bold}"
    c3="$(color "$3")${ascii_bold}"
    c4="$(color "$4")${ascii_bold}"
    c5="$(color "$5")${ascii_bold}"
    c6="$(color "$6")${ascii_bold}"

    [[ "$color_text" != "off" ]] && set_text_colors "$@"
}
# # Start
# printf "\n\n"
# printf "\033[1;${COLOR}m╔╤╤╤╤╤╤╤╤╤╤╤╤╤╤╤╤╗  ╔╤╤╤╤╤╤╗\033[0m
# \033[1;${COLOR}m╟┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼╢  ╟┼┼┼┼┼┼╢\033[0m
# \033[1;${COLOR}m╟┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼╢  ╟┼┼┼┼┼┼╢\033[0m
# \033[1;${COLOR}m╟┼┼┼┼┼┼╔╧╧╧╧╧╧╧╧╧╝  ╟┼┼┼┼┼┼╢\033[0m
# \033[1;${COLOR}m╟┼┼┼┼┼┼╢            ╟┼┼┼┼┼┼╢\033[0m
# \033[1;${COLOR}m╟┼┼┼┼┼┼╢  ╔╤╤╤╤╤╤╗  ╟┼┼┼┼┼┼╢\033[0m
# \033[1;${COLOR}m╟┼┼┼┼┼┼╢  ╟┼┼┼┼┼┼╢  ╟┼┼┼┼┼┼╢\033[0m
# \033[1;${COLOR}m╟┼┼┼┼┼┼╢  ╟┼┼┼┼┼┼╢  ╟┼┼┼┼┼┼╢\033[0m
# \033[1;${COLOR}m╟┼┼┼┼┼┼╢  ╟┼┼┼┼┼┼╢  ╟┼┼┼┼┼┼╢\033[0m
# \033[1;${COLOR}m╟┼┼┼┼┼┼╢  ╟┼┼┼┼┼┼╢  ╟┼┼┼┼┼┼╢\033[0m
# \033[1;${COLOR}m╟┼┼┼┼┼┼╢  ╟┼┼┼┼┼┼╢  ╟┼┼┼┼┼┼╢\033[0m
# \033[1;${COLOR}m╟┼┼┼┼┼┼╢  ╟┼┼┼┼┼┼╢  ╟┼┼┼┼┼┼╢\033[0m
# \033[1;${COLOR}m╟┼┼┼┼┼┼╢  ╟┼┼┼┼┼┼╢  ╟┼┼┼┼┼┼╢\033[0m
# \033[1;${COLOR}m╚╧╧╧╧╧╧╝  ╚╧╧╧╧╧╧╝  ╚╧╧╧╧╧╧╝\033[0m" 

set_colors 6 6 7 1
            read -rd '' ascii_data <<'EOF'
${c1}                   -`
                  .o+`
                 `ooo/
                `+oooo:
               `+oooooo:
               -+oooooo+:
             `/:-:++oooo+:
            `/++++/+++++++:
           `/++++++++++++++:
          `/+++o${c2}oooooooo${c1}oooo/`
${c2}         ${c1}./${c2}ooosssso++osssssso${c1}+`
${c2}        .oossssso-````/ossssss+`
       -osssssso.      :ssssssso.
      :osssssss/        osssso+++.
     /ossssssss/        +ssssooo/-
   `/ossssso+/:-        -:/+osssso+-
  `+sso+:-`                 `.-/+oso:
 `++:.                           `-/+/
 .`                                 `/
EOF| boxes -d jstone\033[0m

exit 0
