#!/usr/bin/env zsh
set -eu

XDG_CONFIG_HOME=$HOME/.config
XDG_CACHE_HOME=$HOME/.cache
XDG_DATA_HOME=$HOME/.local/share
XDG_STATE_HOME=$HOME/.local/state
CARGO_HOME=$XDG_DATA_HOME/cargo
RUSTUP_HOME=$XDG_DATA_HOME/rustup
NPM_CONFIG_USERCONFIG=$XDG_CONFIG_HOME/npm/config
NPM_CONFIG_CACHE=$XDG_CACHE_HOME/npm

# I dont think I need this but, I'm going to keep it for now 
XDG_RUNTIME_DIR=/run/user/$UID
NPM_CONFIG_TMP=$XDG_RUNTIME_DIR/npm

mkdir -p $XDG_CONFIG_HOME/zsh/zplug/repos/zplug/zplug
mkdir -p $XDG_CACHE_HOME/zsh/
mkdir -p $XDG_DATA_HOME/ls_colors
mkdir -p $XDG_STATE_HOME
mkdir -p $CARGO_HOME
mkdir -p $RUSTUP_HOME
mkdir -p $HOME/.local/bin
mkdir -p $HOME/.local/games
mkdir -p $XDG_CONFIG_HOME/bfetch
mkdir -p $XDG_CONFIG_HOME/boxes
mkdir -p $XDG_CONFIG_HOME/git
mkdir -p $XDG_CONFIG_HOME/lsd
mkdir -p $XDG_CONFIG_HOME/nvim
mkdir -p $XDG_CONFIG_HOME/kitty

pushd $XDG_DATA_HOME
git clone --recurse-submodules git@github.com:jdsurrett/dotfiles.git dotfiles
popd

pushd $XDG_DATA_HOME/dotfiles
stow -vt $HOME stow
stow -vt $HOME zsh bfetch git boxes lsd ls_colors_pack bin

curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
source $XDG_DATA_HOME/cargo/env
rm -f $HOME/.profile

bash <(curl -s https://raw.githubusercontent.com/lunarvim/lunarvim/master/utils/installer/install.sh) -y
rm -rf $XDG_CONFIG_HOME/lvim/*
stow -vt $HOME lvim
popd

pushd $HOME/.local/bin
curl -LO https://raw.githubusercontent.com/jnats/nofetch/main/nofetch
chmod +x nofetch
popd

pushd $XDG_CONFIG_HOME/boxes
curl -LO https://raw.githubusercontent.com/ascii-boxes/boxes/master/boxes-config
popd

lvim -c "PackerInstall" -c "PackerCompile"
