#!/usr/bin/env zsh

source $ZDOTDIR/zplug/init.zsh
zplug 'zplug/zplug', hook-build:'zplug --self-manage'
zplug 'romkatv/powerlevel10k', as:theme, depth:1
zplug "lib/history", from:oh-my-zsh
zplug "plugins/sudo", from:oh-my-zsh
zplug "modules/completion", from:prezto
zplug "lib/key-bindings", from:oh-my-zsh:
zplug "lib/clipboard", from:oh-my-zsh:
zplug "zsh-users/zsh-completions"
zplug "zsh-users/zsh-syntax-highlighting", defer:2
zplug "zsh-users/zsh-autosuggestions"
if ! zplug check --verbose; then
    printf "Install? [y/N]: "
    if read -q; then
        echo; zplug install
    fi
fi
zplug load

export HISTFILE=$XDG_CACHE_HOME/zsh_history
source $ZDOTDIR/p10k.zsh
typeset -U PATH path=("$HOME/.local/bin" "$path[@]")
export PATH
source $ZDOTDIR/aliases.zsh
clear
