#!/usr/bin/env zsh

source $ZDOTDIR/plugins/romkatv/powerlevel10k/powerlevel10k.zsh-theme
source $ZDOTDIR/plugins/sorin-ionescu/prezto/completion/init.zsh
source $ZDOTDIR/plugins/zsh-users/zsh-autosuggestions/zsh-autosuggestions.zsh
source $ZDOTDIR/plugins/zsh-users/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
clear
