#!/usr/bin/env zsh

source $ZDOTDIR/p10k.zsh
source $ZDOTDIR/plugins/romkatv/powerlevel10k/powerlevel10k.zsh-theme
source $ZDOTDIR/plugins/ohmyzsh/history.zsh
source $ZDOTDIR/plugins/ohmyzsh/sudo.plugin.zsh
source $ZDOTDIR/plugins/ohmyzsh/key-bindings.zsh
source $ZDOTDIR/plugins/ohmyzsh/clipboard.zsh
source $ZDOTDIR/plugins/sorin-ionescu/prezto/completion/init.zsh
source $ZDOTDIR/plugins/zsh-users/zsh-autosuggestions/zsh-autosuggestions.zsh
source $ZDOTDIR/plugins/zsh-users/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

export HISTFILE=$XDG_CACHE_HOME/zsh_history
typeset -U PATH path=("$HOME/.local/bin" "$path[@]")
export PATH
source $ZDOTDIR/aliases.zsh
clear
