[pyprland]
plugins = ["scratchpads"]

[scratchpads.term_quake]
command = "kitty --class term_quake --start-as fullscreen"
size = "100% 100%"
class = "term_quake"
animation = "fromTop"
multi = "false"
pinned = "true"
lazy = "true"