#!/usr/bin/env zsh
waylogout \
	--inside-color=88888866 \
	--text-color=eaeaeaaa \
	--line-color=00000000 \
	--ring-selection-color=33cc33aa \
	--inside-selection-color=33cc3366 \
	--text-selection-color=eaeaeaaa \
	--line-selection-color=00000000 \
	--lock-command="~/.local/share/scripts/swaylock_handler" \
	--poweroff-command="systemctl poweroff" \
	--reboot-command="systemctl reboot" \
	--selection-label
