#!/usr/bin/env zsh
swaylock_handler () 
{
    swaylock \
        --screenshots \
        --clock \
        --indicator \
        --indicator-radius 100 \
        --indicator-thickness 7 \
        --effect-blur 7x5 \
        --effect-vignette 0.5:0.5 \
        --ring-color bb00cc \
        --key-hl-color 880033 \
        --line-color 00000000 \
        --inside-color 00000088 \
        --separator-color 00000000 \
        --fade-in 0.2
}

waylogout \
	--indicator-thickness=20 \
	--ring-color=888888aa \
	--inside-color=88888866 \
	--text-color=eaeaeaaa \
	--line-color=00000000 \
	--ring-selection-color=33cc33aa \
	--inside-selection-color=33cc3366 \
	--text-selection-color=eaeaeaaa \
	--line-selection-color=00000000 \
    --lock-command=swaylock_handler() \
	--poweroff-command="systemctl poweroff" \
	--reboot-command="systemctl reboot" \
	--selection-label
