#!/usr/bin/env zsh

alias wget=wget --hsts-file="$XDG_DATA_HOME/wget-hsts"
alias vim="nvim"
alias vi="nvim"
alias v="nvim"
alias nvimtutor="nvim -c :Tutor"
alias vimtutor="nvim -c :Tutor"
alias vitutor="nvim -c :Tutor"
alias vtutor="nvim -c :Tutor"
alias ls="lsd"
alias la="lsd -l --almost-all"
alias tree="lsd -l --almost-all --tree"
alias ll="lsd -l"
alias xs="sl -l"
alias vf="sl -f"
alias cl="sl -Fla"
alias holly="sl -Fla"
alias vl="sl -Fla"
alias tclear="tput clear"
alias dmenu="wofi --dmenu"
