#!/usr/bin/env zsh

export XDG_STATE_HOME=$HOME/.local/state
export XDG_DATA_HOME=$HOME/.local/share
export MANDIR=$XDG_DATA_HOME/man:/usr/local/share/man
source $XDG_DATA_HOME/ls_colors/lscolors.sh
export GOPATH="$XDG_DATA_HOME"/go
export GNUPGHOME="$XDG_DATA_HOME"/gnupg

export XDG_CONFIG_HOME=$HOME/.config
export NPM_CONFIG_USERCONFIG=$XDG_CONFIG_HOME/npm/config

export XDG_CACHE_HOME=$HOME/.cache
export NPM_CONFIG_CACHE=$XDG_CACHE_HOME/npm
export BAT_CONFIG_PATH=$XDG_CONFIG_HOME/bat
export KITTY_CONFIG_DIRECTORY=$XDG_CONFIG_HOME/kitty
export RUSTUP_HOME=$XDG_DATA_HOME/rustup
export CARGO_HOME="$XDG_DATA_HOME"/cargo

export COMPLETION_WAITING_DOTS="%F{yellow}waiting...%f"

export EDITOR=${HOME}/.local/bin/lvim

export COMMON_FLAGS="-march=native -mtune=native -O2 -pipe"
export CFLAGS="${COMMON_FLAGS}"
export CXXFLAGS="${COMMON_FLAGS}"
export MAKEOPTS="-j$(nproc)"

export BFETCH_CLASSIC_MODE=true
export BFETCH_ART_RIGHT=true
export BFETCH_SEPARATOR=0
typeset -U PATH path=("$HOME/.local/bin" "$path[@]")
export PATH
export MOZ_ENABLE_WAYLAND="1"
export XDG_CURRENT_DESKTOP=sway
export XDG_SESSION_TYPE=wayland
export QT_QPA_PLATFORM="wayland-egl"
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
