#!/usr/bin/env zsh

# . "$CARGO_HOME/env"
# typeset -U PATH path=("$HOME/.local/bin" "$HOME/.local/share/gem/ruby/3.0.0/bin" "$path[@]")
# export PATH

case "$DESKTOP_SESSION" in
    i3|sway)
        export $(gnome-keyring-daemon --start)
        export MOZ_ENABLE_WAYLAND="1"
        export XDG_CURRENT_DESKTOP=sway
        export XDG_SESSION_TYPE=wayland
        export QT_QPA_PLATFORM="wayland-egl"

        ;;
esac
